sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t owen2709/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run USERNAME/react-test npm test -- --coverage

after_success:
  - docker build -t owen2709/multi-client ./client
  - docker build -t owen2709/multi-nginx ./nginx
  - docker build -t owen2709/multi-server ./server
  - docker build -t owen2709/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push owen2709/multi-client
  - docker push owen2709/multi-nginx
  - docker push owen2709/multi-server
  - docker push owen2709/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-2'
  bucket_name: 'elasticbeanstalk-us-east-2-937699517699'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY